import type { Doctor, Testimonial, Faq, Appointment, NewsArticle, Service } from '@/types';

export const servicesData: Service[] = [
  {
    id: 'dental-implants',
    title: 'Dental Implants',
    desc: 'Foundation for replacement teeth that look, feel, and function like natural teeth.',
    fullDesc:
      'Dental implants are changing the way people live. They are designed to provide a foundation for replacement teeth that look, feel, and function like natural teeth. The person who has lost teeth regains the ability to eat virtually anything and can smile with confidence.',
    price: 'Custom Quote',
    iconName: 'ShieldCheck',
    color: 'text-teal-50',
    bg: 'bg-white/20 backdrop-blur-md',
    cardBg: 'bg-gradient-to-br from-teal-500 to-cyan-600 border-teal-400 text-white',
    btnBg: 'bg-white text-teal-700 hover:bg-teal-50',
    shadow: 'shadow-teal-500/20 hover:shadow-teal-500/40',
    process: [
      'Clinical Consultation & 3D Imaging',
      'Surgical Implant Placement',
      'Osseointegration (Healing)',
      'Prosthetic Crown Attachment',
    ],
  },
  {
    id: 'invisalign',
    title: 'Invisalign',
    desc: 'Straighten teeth using custom-made clear braces that gently pull them into position.',
    fullDesc:
      'Invisalign is an orthodontic treatment that straightens teeth by using custom-made clear braces that cover your teeth and gently pull them into the proper position over time. Because they are clear and removable, they are far less noticeable and more convenient than traditional braces.',
    price: 'From ₹75,000',
    iconName: 'Star',
    color: 'text-cyan-50',
    bg: 'bg-white/20 backdrop-blur-md',
    cardBg: 'bg-gradient-to-br from-cyan-500 to-blue-600 border-cyan-400 text-white',
    btnBg: 'bg-white text-cyan-700 hover:bg-cyan-50',
    shadow: 'shadow-cyan-500/20 hover:shadow-cyan-500/40',
    process: [
      'Digital 3D Oral Scan',
      'Custom Aligner Fabrication',
      'Initial Clinical Fitting',
      'Progress Monitoring',
    ],
  },
  {
    id: 'smile-makeover',
    title: 'Smile Makeover',
    desc: 'Cosmetic procedure that changes appearance and restores optimal dental function.',
    fullDesc:
      'Smile makeover is a cosmetic dental procedure that not only changes the appearance of your teeth, smile, or bite but also optimizes and restores your function. We combine multiple advanced treatments to give you the perfect, radiant smile you deserve.',
    price: 'Consultation Free',
    iconName: 'Sparkles',
    color: 'text-amber-50',
    bg: 'bg-white/20 backdrop-blur-md',
    cardBg: 'bg-gradient-to-br from-amber-500 to-orange-500 border-amber-400 text-white',
    btnBg: 'bg-white text-amber-700 hover:bg-amber-50',
    shadow: 'shadow-amber-500/20 hover:shadow-amber-500/40',
    process: [
      'Aesthetic & Clinical Evaluation',
      'Digital Smile Design',
      'Preparatory Dental Treatments',
      'Final Restorations',
    ],
  },
  {
    id: 'orthodontics',
    title: 'Orthodontic Treatment',
    desc: 'Address misaligned teeth early for perfect chewing, biting, and speaking.',
    fullDesc:
      "Address your child's misaligned teeth as early as they can chew, bite and speak normally. For children's and adult orthodontics, our expert team is here for you and your family, utilizing the latest in both traditional and invisible alignment technology.",
    price: 'Consultation Free',
    iconName: 'Smile',
    color: 'text-blue-50',
    bg: 'bg-white/20 backdrop-blur-md',
    cardBg: 'bg-gradient-to-br from-blue-500 to-indigo-600 border-blue-400 text-white',
    btnBg: 'bg-white text-blue-700 hover:bg-blue-50',
    shadow: 'shadow-blue-500/20 hover:shadow-blue-500/40',
    process: [
      'Comprehensive Orthodontic Assessment',
      'Treatment Planning',
      'Appliance Placement',
      'Routine Clinical Adjustments',
    ],
  },
  {
    id: 'root-canal',
    title: 'Root Canal Treatment',
    desc: 'Prevent tooth loss by removing infected tissue and sealing with biocompatible material.',
    fullDesc:
      'Root canal treatment is a procedure intended to prevent tooth loss and a widespread infection by removing the infected pulp tissue, cleaning and filling the canals with a biocompatible material. Our advanced techniques make this process practically painless.',
    price: 'From ₹4,000',
    iconName: 'Activity',
    color: 'text-rose-50',
    bg: 'bg-white/20 backdrop-blur-md',
    cardBg: 'bg-gradient-to-br from-rose-500 to-pink-600 border-rose-400 text-white',
    btnBg: 'bg-white text-rose-700 hover:bg-rose-50',
    shadow: 'shadow-rose-500/20 hover:shadow-rose-500/40',
    process: [
      'Digital Radiography & Diagnosis',
      'Local Anesthesia Administration',
      'Endodontic Infection Removal',
      'Sealing & Crown Placement',
    ],
  },
  {
    id: 'laser-whitening',
    title: 'Laser Teeth Whitening',
    desc: 'Lighten teeth to a brighter color using strong dental gel activated by a laser.',
    fullDesc:
      'Laser teeth whitening is a technique that lightens teeth to a whiter and brighter color with the use of a strong dental bleaching gel that is activated by a laser beam. Achieve a stellar, radiant smile in just a single one-hour visit.',
    price: 'From ₹8,000',
    iconName: 'Zap',
    color: 'text-sky-50',
    bg: 'bg-white/20 backdrop-blur-md',
    cardBg: 'bg-gradient-to-br from-sky-500 to-cyan-600 border-sky-400 text-white',
    btnBg: 'bg-white text-sky-700 hover:bg-sky-50',
    shadow: 'shadow-sky-500/20 hover:shadow-sky-500/40',
    process: [
      'Clinical Shade Assessment',
      'Gingival Protection',
      'Laser Gel Application',
      'Final Enamel Polish',
    ],
  },
];

export const comprehensiveCategories = [
  {
    title: 'General Dentistry',
    bgClass: 'from-emerald-100 to-white border-emerald-200 shadow-emerald-500/10 hover:shadow-emerald-500/20',
    titleClass: 'border-emerald-200 text-emerald-800',
    iconClass: 'text-emerald-600',
    items: [
      'Comprehensive Oral Exams',
      'Routine Teeth Cleaning',
      'Deep Cleaning for Teeth & Gums',
      'Composite Fillings',
      'Dental Inlays & Onlays',
      'Periodical Care',
      'Preventive Dentistry',
      'Orthodontic Treatment',
      'Pediatric Dentistry Care',
      'Root Canal Treatment',
      'Tooth Extractions',
      'Wisdom Tooth Removal',
    ],
  },
  {
    title: 'Cosmetic Dentistry',
    bgClass: 'from-amber-100 to-white border-amber-200 shadow-amber-500/10 hover:shadow-amber-500/20',
    titleClass: 'border-amber-200 text-amber-800',
    iconClass: 'text-amber-600',
    items: [
      'Invisalign Clear Aligners',
      'Complete Smile Makeovers',
      'Ceramic Veneers',
      'Laser Teeth Whitening',
      'Enamel Reshaping',
      'Dental Bonding',
      'Gummy Smile Correction',
    ],
  },
  {
    title: 'Restorative Dentistry',
    bgClass: 'from-teal-100 to-white border-teal-200 shadow-teal-500/10 hover:shadow-teal-500/20',
    titleClass: 'border-teal-200 text-teal-800',
    iconClass: 'text-teal-600',
    items: [
      'Dental Crowns & Bridges',
      'Dental Implants',
      'Implant-Supported Crowns',
      'Removable Dentures',
      'Snap-On Dentures',
      'Fixed Dentures',
      'Full Mouth Rehabilitation',
      'All-On-Four Implants',
    ],
  },
];

export const initialDoctors: Doctor[] = [
  {
    id: 'dr-poojitha-pasupuleti',
    name: 'Dr. Poojitha Pasupuleti',
    role: 'Resident Dental Surgeon',
    img_url: 'https://images.unsplash.com/photo-1594824436998-ef22497d7681?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    bio: 'Dr. Poojitha is dedicated to providing comprehensive and compassionate routine dental care. With a focus on preventive dentistry, she ensures every patient maintains optimal oral health through meticulous diagnostics and patient education.',
    credentials: ['BDS', 'Certified in Preventive Dentistry', 'Advanced Diagnostics Training'],
    specialty: 'General Dentistry',
    specializations: ['Routine Oral Care', 'Preventive Dentistry', 'Comprehensive Exams', 'Composite Fillings'],
    rating: '4.8',
    reviews: 124,
    quote: 'Preventive care today ensures a healthy, radiant smile for a lifetime.',
  },
  {
    id: 'dr-anjali-raval',
    name: 'Dr. Anjali Raval',
    role: 'MDS - Prosthodontist & Implantologist',
    img_url: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    bio: 'Dr. Anjali specializes in restoring oral function and aesthetics. Her profound expertise in prosthodontics and implantology allows her to craft perfect, natural-looking replacements that seamlessly integrate with your smile.',
    credentials: ['MDS in Prosthodontics', 'Certified Implantologist', 'Specialist in Full-Mouth Restorations'],
    specialty: 'Prosthodontics & Implants',
    specializations: ['Dental Implants', 'Crowns & Bridges', 'Removable/Fixed Dentures', 'Full Mouth Rehabilitation'],
    rating: '4.9',
    reviews: 210,
    quote: 'Restoring your smile is about restoring your confidence and overall quality of life.',
  },
  {
    id: 'dr-prahlad-shenava',
    name: 'Dr. Prahlad Shenava',
    role: 'MDS - Orthodontist & Invisalign Specialist',
    img_url: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    bio: 'Dr. Prahlad is passionate about the biomechanics of a perfect bite. Specializing in advanced clear aligners and traditional orthodontics, he crafts customized treatment trajectories that are highly efficient and transformative.',
    credentials: ['MDS in Orthodontics', 'Certified Invisalign Specialist', 'Expert in Craniofacial Biomechanics'],
    specialty: 'Orthodontics',
    specializations: ['Invisalign Clear Aligners', 'Traditional Braces', 'Complex Bite Correction', 'Adult Orthodontics'],
    rating: '5.0',
    reviews: 318,
    quote: 'A perfectly aligned smile is the greatest foundation for lifelong oral health.',
  },
  {
    id: 'dr-yogesh-reddy',
    name: 'Dr. Yogesh Reddy',
    role: 'MDS - Endodontist & Esthetic Dentist',
    img_url: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    bio: 'Dr. Yogesh brings unparalleled precision to root canal therapies and cosmetic enhancements. His dual expertise ensures that saving a natural tooth also means keeping it looking flawless and structurally sound.',
    credentials: ['MDS in Endodontics', 'Advanced Certification in Esthetic Dentistry', 'Microscopic Endodontics Specialist'],
    specialty: 'Endodontics & Esthetics',
    specializations: ['Painless Root Canals', 'Smile Makeovers', 'Porcelain Veneers', 'Dental Trauma Management'],
    rating: '4.9',
    reviews: 185,
    quote: 'Saving a tooth through precision endodontics is always our first priority.',
  },
  {
    id: 'dr-swati-reddy',
    name: 'Dr. Swati Reddy',
    role: 'MDS - Pedodontist',
    img_url: 'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    bio: 'Dr. Swati specializes in the unique dental needs of children. With a gentle, anxiety-free approach, she ensures early dental experiences are positive, laying the groundwork for a lifetime of excellent oral hygiene habits.',
    credentials: ['MDS in Pedodontics', 'Specialist in Child Dental Care', 'Certified in Conscious Sedation'],
    specialty: 'Pediatric Dentistry',
    specializations: ['Child Preventive Care', 'Early Interceptive Orthodontics', 'Painless Milk Tooth Extractions', 'Fluoride & Sealants'],
    rating: '5.0',
    reviews: 256,
    quote: "A child's positive early dental experience sets the tone for their future health.",
  },
  {
    id: 'dr-ashish-sharma',
    name: 'Dr. Ashish Sharma',
    role: 'MDS - Periodontist & Implantologist',
    img_url: 'https://images.unsplash.com/photo-1590611936760-eeb9bc50228d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    bio: 'Dr. Ashish is dedicated to the foundational health of your smile. Specializing in gum health and complex implantology, he utilizes advanced techniques to treat periodontal disease and provide secure, lasting bases for dental implants.',
    credentials: ['MDS in Periodontics', 'Certified Implantologist', 'Expert in Soft Tissue Grafting'],
    specialty: 'Periodontics & Implants',
    specializations: ['Advanced Gum Therapy', 'Dental Implants', 'Bone & Tissue Grafting', 'Laser Periodontics'],
    rating: '4.8',
    reviews: 142,
    quote: 'Healthy gums are the essential foundation in which a beautiful smile can grow.',
  },
  {
    id: 'dr-shameel-ahmed-shariff',
    name: 'Dr. Shameel Ahmed Shariff',
    role: 'MDS(OMFS) - Consultant OMFS & Implantologist',
    img_url: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    bio: 'Dr. Shameel specializes in complex oral and maxillofacial surgeries. From impacted wisdom teeth extractions to advanced reconstructive implantology, his extensive surgical training ensures safe, comfortable, and highly successful outcomes.',
    credentials: ['MDS in Oral & Maxillofacial Surgery', 'Consultant OMFS', 'Advanced Implantology Surgeon'],
    specialty: 'Oral & Maxillofacial Surgery',
    specializations: ['Wisdom Tooth Removal', 'Complex Maxillofacial Surgery', 'Surgical Implant Placements', 'Jaw Reconstruction'],
    rating: '4.9',
    reviews: 198,
    quote: 'Surgical excellence is about combining technical mastery with utmost patient comfort.',
  },
  {
    id: 'dr-prashant',
    name: 'Dr. Prashant',
    role: 'MDS - Endodontist',
    img_url: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    bio: 'Dr. Prashant specializes in diagnosing and treating complex tooth pain and performing advanced root canal treatments. He is dedicated to saving natural teeth using the latest micro-endodontic technology, ensuring patients experience minimal discomfort and exceptional clinical results.',
    credentials: ['MDS in Endodontics', 'Micro-Endodontics Specialist', 'Expert in Pain Management'],
    specialty: 'Endodontics',
    specializations: ['Painless Root Canal Therapy', 'Endodontic Retreatment', 'Dental Trauma Care', 'Apicoectomy'],
    rating: '4.9',
    reviews: 165,
    quote: 'Preserving your natural smile through painless, highly precise care is my ultimate goal.',
  },
  {
    id: 'dr-zubair',
    name: 'Dr. Zubair',
    role: 'MDS - Oral Maxillofacial Surgeon',
    img_url: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
    bio: 'Dr. Zubair is a highly skilled Oral and Maxillofacial Surgeon with extensive clinical experience in surgical extractions, facial trauma, and complex implant procedures. He prioritizes patient safety, precise surgical planning, and rapid recovery in every intervention.',
    credentials: ['MDS in Oral & Maxillofacial Surgery', 'Advanced Surgical Implantology', 'Trauma & Reconstructive Surgery'],
    specialty: 'Oral & Maxillofacial Surgery',
    specializations: ['Impacted Wisdom Tooth Extraction', 'Advanced Dental Implants', 'Maxillofacial Trauma', 'Bone Grafting'],
    rating: '4.8',
    reviews: 182,
    quote: 'Expert surgical care combined with a compassionate approach ensures the best possible recovery.',
  },
];

export const initialTestimonials: Testimonial[] = [
  {
    id: 1,
    text: 'COSMO DENTAL completely elevated my dental routine. From my pristine implants to the flawless root canal, I look and feel amazing.',
    author: 'Sarah Jenkins',
    role: 'Restorative Patient',
    rating: 5,
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-4.0.3&w=150&q=80',
  },
  {
    id: 2,
    text: 'The smile makeover transformed my confidence perfectly, and their laser tech is unmatched. Truly the best dental clinic in Sarjapur road.',
    author: 'Marcus Thorne',
    role: 'Cosmetic Patient',
    rating: 5,
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&w=150&q=80',
  },
  {
    id: 3,
    text: 'I used to have severe clinic anxiety. The calming clinical environment and their incredibly transparent, expert care completely cured my fear.',
    author: 'Elena Rostova',
    role: 'General Care',
    rating: 5,
    avatar_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-4.0.3&w=150&q=80',
  },
  {
    id: 4,
    text: 'Best orthodontics experience for my teenager near Kodathi gate. The invisible aligners worked exactly as predicted. Highly recommend the team here.',
    author: 'David Chen',
    role: 'Parent',
    rating: 5,
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-4.0.3&w=150&q=80',
  },
];

export const initialFaqs: Faq[] = [
  {
    id: 1,
    question: 'Do you accept dental and medical insurance?',
    answer: 'Yes, we accept a wide variety of major dental and medical insurance plans. Our clinical patient coordinators will help you maximize your health benefits during your visit.',
  },
  {
    id: 2,
    question: 'What should I expect on my first clinical visit?',
    answer: 'Your first visit includes a comprehensive oral evaluation, 3D mapping of your dental structure, and a customized treatment plan designed by our expert medical team to deliver optimal oral health.',
  },
  {
    id: 3,
    question: 'Is professional laser teeth whitening safe for my enamel?',
    answer: 'Absolutely. Our professional dental whitening procedures use advanced, safe light frequencies that lift surface stains without damaging the structural integrity of your enamel.',
  },
  {
    id: 4,
    question: 'Do these dental procedures require significant recovery time?',
    answer: 'At COSMO DENTAL, we prioritize state-of-the-art medical technology that provides maximum transformative clinical results with minimal to zero downtime, getting you back to your routine quickly.',
  },
];

export const initialAppointments: Appointment[] = [
  {
    id: 101,
    name: 'Alice Vanderbilt',
    email: 'alice@example.com',
    phone: '9876543210',
    service: 'Invisalign',
    date: '2026-04-24',
    status: 'Confirmed',
  },
  {
    id: 102,
    name: 'John Smith',
    email: 'john.s@example.com',
    phone: '9123456789',
    service: 'Dental Implants',
    date: '2026-04-25',
    status: 'Pending',
  },
];

export const initialGalleryImages: string[] = [
  'https://images.unsplash.com/photo-1629909613654-28e377c37b09?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1600170311833-c2cf5280ce49?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1609840114035-3c981b782dfe?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1590664095641-7fa05f689813?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
];

export const initialNews: NewsArticle[] = [
  {
    id: 1,
    title: 'The Future of AI in Orthodontics',
    date: 'April 12, 2026',
    author: 'Dr. Prahlad Shenava',
    category: 'Technology',
    img_url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
    excerpt: 'How predictive modeling and 3D scanning are making treatments more precise than ever.',
    content:
      "Artificial Intelligence is no longer just a concept; it's a daily reality in modern dentistry. At COSMO DENTAL, we utilize AI-driven algorithms to map your oral cavity with microscopic precision. This allows us to predict how teeth will shift over time and tailor aligners perfectly. By integrating these systems, we deliver maximum clinical results with minimal chair time.",
  },
  {
    id: 2,
    title: 'Why Dental Implants are Changing Lives',
    date: 'March 28, 2026',
    author: 'Dr. Anjali Raval',
    category: 'Treatments',
    img_url: 'https://images.unsplash.com/photo-1598256989800-fea5ce5146f2?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
    excerpt: 'Discover the unseen benefits of permanent replacements over traditional dentures.',
    content:
      "For decades, removable dentures were the only reliable path to restoring a full smile. Today, Dental Implants have changed the field. Made from medical-grade titanium, these posts fuse with your jawbone. The benefits aren't just aesthetic; they prevent bone loss, restore full chewing power, and never slip or click while you speak. It is a true, permanent return to function.",
  },
  {
    id: 3,
    title: 'Maintaining Your Oral Health Daily',
    date: 'March 15, 2026',
    author: 'Dr. Poojitha Pasupuleti',
    category: 'Oral Health',
    img_url: 'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80',
    excerpt: 'Daily habits and modern tools to keep your enamel strong and your gums healthy.',
    content:
      "Keeping your smile stellar between clinical visits requires daily dedication. We recommend brushing twice daily using an ultrasonic toothbrush, which operates at frequencies high enough to disrupt plaque colonies even slightly beyond the bristles' reach. Flossing is non-negotiable; consider water flossers to clear interdental debris gently. Lastly, limit highly acidic and sugary foods which can erode enamel over time.",
  },
];

export const technologyEquipment = [
  { name: 'Digital X-Rays', iconName: 'Activity', color: 'text-emerald-600', bg: 'bg-emerald-100/50' },
  { name: 'Intra-Oral Cameras', iconName: 'Camera', color: 'text-teal-600', bg: 'bg-teal-100/50' },
  { name: 'Intra-Oral Scanners', iconName: 'Zap', color: 'text-amber-600', bg: 'bg-amber-100/50' },
  { name: 'Virtual Implant Planning', iconName: 'ShieldCheck', color: 'text-blue-600', bg: 'bg-blue-100/50' },
  { name: 'Digital Smile Design', iconName: 'Smile', color: 'text-purple-600', bg: 'bg-purple-100/50' },
  { name: 'Dental Laser', iconName: 'Sparkles', color: 'text-rose-600', bg: 'bg-rose-100/50' },
  { name: 'Design Workstations', iconName: 'Laptop', color: 'text-indigo-600', bg: 'bg-indigo-100/50' },
  { name: 'Virtual Consultation', iconName: 'Video', color: 'text-sky-600', bg: 'bg-sky-100/50' },
  { name: 'Guided Implant Surgery', iconName: 'Crosshair', color: 'text-emerald-600', bg: 'bg-emerald-100/50' },
  { name: '42" 4K TV Screens', subtitle: 'For Patient Education', iconName: 'Tv', color: 'text-slate-600', bg: 'bg-slate-100/50' },
];
